# Generated by Django 3.0.6 on 2020-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antonyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'antonyme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('taux_de_validation', models.IntegerField()),
                ('exemple', models.CharField(blank=True, max_length=2000, null=True)),
                ('reference', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListeApprentissage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'liste_apprentissage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orthographe', models.CharField(max_length=255)),
                ('nature_grammaticale', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('etymologie', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Mot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'reponse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonyme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'synonyme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TermeDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'terme_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UniteTerminologique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'unite_terminologique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=40)),
                ('mot_de_passe', models.CharField(max_length=40)),
                ('date_inscription', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
    ]
